### ISSUE TITLE
Ignorelist.txt doesn't automatically update if the download fails

### ISSUE THREAD

**Issue by RowanSkie** [nianeyna/ao3downloader#136]

**Comment by nianeyna** [comment]
Hm, this is an interesting one. The problem here is that some people may *not* want to automatically update the ignorelist, so I don't think I would add this as a default. But, adding new options to the ini is a bit involved. So... unfortunately I'm gonna say wontfix on this one. To get around it you should be able to just quickly run the ignorelist configuration option after a download - if that doesn't work as expected, let me know and I will reopen this issue!

**Comment by RowanSkie** [comment]
Oh wow, it's almost a month.

I found the cause of my problem (and this issue) by digging through the source code. It checks for an error that says "Deleted", when the error that only appears is `"error": "'NoneType' object has no attribute 'find'"`.
