### ISSUE TITLE
Urls aren't saved when there is an exception

### ISSUE THREAD

**Issue by JediMaster25** [nianeyna/ao3downloader#49]
I think it should save the urls as it finds them into a file so that they stay there in case of an exception.

**Comment by nianeyna** [comment]
Yeah. The link grabber is pretty fragile at the moment - I slapped it together pretty quickly in response to a user request and it shows, unfortunately. Saving the links incrementally would cause duplication issues, especially with the series option, but I can (and should, you're right) add some error handling so that you don't just lose the whole list if something goes wrong.
