### ISSUE TITLE
Request: Ignore Incomplete Fic That Did Not Update When Running Updating

### ISSUE THREAD

**Issue by readingfan** [nianeyna/ao3downloader#78]
Hello,

Thank you for creating the AO3 Downloader! It has been incredibly helpful in creating my library. I was wondering however if there is a way to make updating the folder faster?

I have 55000 works and of those according to the program I have 4950 in progress works. This takes some 9+ hours to run the program for that. There is basically a 5 min downtime between every 70 works downloaded. But obviously since not all of those would be updating I generally get maybe between 150 of the 4950 works or so get updated at most after the 9 hours of the program running.

I was wondering if there is a way to improve the speed by ignoring works that were last updated in 2015 and just update the ones that had chapters added since the last update?

Ex: Ignore: The Sea - Fandom - 35/? - last Update: 1/1/2015 but take The Sea - Fandom -36? - Last Update 4/23/2023 should it update?

Even if it would take some time to sort out the works I think if this was possible it would improve the speed greatly since the older WIP works may get updated but sometimes are just  discontinued, so why re-download if there is no update?

P.S. A question:  if a work is marked complete but gets new chapters does it get updated too? I noticed that some authors mark a work as complete, but sometimes add on in the same story as extras. Does that get updated too?

Thank you for your hard work on this program. I understand if this is not possible but still had to ask.

I hope you have a great day.

**Comment by nianeyna** [comment]
There is an "ignore list" function where you could add works that you are really sure are abandoned and won't ever be updated again, so that they will always be skipped and not take up bandwidth. Otherwise, unfortunately, there is no way to avoid hitting ao3 for every incomplete work, because there is no other possible way to know if there have been new chapters added or not (works without new chapters are already not downloaded! but the work page itself still has to be checked in order to make that decision).

To your other question - so, in order to detect whether a work is incomplete, the downloader actually just checks the bit where it says "Chapters: xx/yy". If in the current version you have downloaded, xx is the same number as yy, the downloader WILL NOT check for updates, so if the author decides to add another chapter after that, you would need to manually re-download. If xx is *different* from yy (including if yy is a question mark) then the downloader will always check for updates, unless you have added the work url to the ignore list. I hope that makes sense!
