### ISSUE TITLE
Several issues, possibly related

### ISSUE THREAD

**Issue by SneaselSupremacy** [nianeyna/ao3downloader#92]
Hello! I have been trying out this new app, so some of these may be growing pains - so sorry if they are! I'm very grateful for this so far, it's worked wonderfully for several fics. I've just noticed some issues I'm having, and wondering if in some way they may be linked. I've tried with both Python 3.11.4 and Python 3.9.0 with the same results. Again - this doesn't necessary break the app! It just has a bit of character. :)

**Issues seen:**
1 When downloading a fic, some of the options don't seem to make any difference. I can say n to downloading fics in a series, and it will still download the sequel. I can say download 2 pages, and all 10 chapters will be saved. 
2 One of the fics I have tried downloading has many links to other fics on it - no amount of telling it not to download other items has made a difference. I have even added the linked fics to the ignore list, and it still downloads. 
3 For that same fic, it downloads the sequel and all of the linked fics, but goes into an infinite loop before it downloads the fic itself. I suspect this may be due to the fact that there's a link to a user's profile in the Chapter Comments section, since that's mentioned in known issue 1. Not sure if it's supposed to try to follow that or not. (Fic for points 2 and 3: https://archiveofourown.org/works/20049589/chapters/47480461 )
4  Another fic just fails to download. I'm not entirely sure why, and the logs seem devoid of any useful information. It doesn't crash or loop or anything, just returns to the menu. (Fic for point 4: https://archiveofourown.org/works/43168005/chapters/108493956 )

Thank you for your time, and I hope you have a wonderful day or night!
-Cassie

**Comment by nianeyna** [comment]
It sounds like you are giving it individual work links? For heaven's sake why? 😂 If you want to download fics from ao3 one by one you can just do that from ao3 itself:

![image](https://github.com/nianeyna/ao3downloader/assets/86076906/c276b0ac-13f0-4439-8638-9a9e938225fa)

That said, if you are really determined to use ao3downloader this way, I think your problems should be solved by entering the link to the work without the chapter identifier, for example: https://archiveofourown.org/works/43168005 instead of https://archiveofourown.org/works/43168005/chapters/108493956

(If I've misunderstood and these examples are just the problems you noticed when downloading a search result or bookmarks etc, please let me know the actual link you entered into the downloader.)

**Comment by SneaselSupremacy** [comment]
Oh my goodness - I think I underestimated this tool, and am blind as a bat to boot! Thank you so much for pointing this out :) Terribly sorry for having wasted your time!
